# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        ('accounts', '0006_profile_current_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allowed_checks',
            field=models.ManyToManyField(to='api.Check'),
        ),
    ]
