# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170314_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userallowedchecks',
            old_name='check',
            new_name='check_id',
        ),
    ]
