# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20170314_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAllowedChecks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Check')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userallowedchecks',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userallowedchecks',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserAllowedChecks',
        ),
    ]
