# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20160415_1824'),
        ('accounts', '0010_auto_20170314_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberallowedchecks',
            name='check_id',
        ),
        migrations.AddField(
            model_name='memberallowedchecks',
            name='checks',
            field=models.ManyToManyField(to='api.Check'),
        ),
    ]
