# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-06 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20170302_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('unresolved', 'unresolved')], default='new', max_length=6),
        ),
    ]
